### PR TITLE
Detect woocommerce and polylang if installed as mu-plugins

### LINKED ISSUE #312: Utilities::polylangVersionCheck fails on composer installations
I was shocked to see this code.

```php
        $filepath = ABSPATH . 'wp-content/plugins/polylang/polylang.php';
        if (! file_exists($filepath)) {
            $filepath = ABSPATH . 'wp-content/plugins/polylang-pro/polylang.php';
            if (! file_exists($filepath)) {
                error_log('Polylang version not tested - polylang file not found');
                return true;
            }
        }
```

The reason is that the `wp-content` folder does not need to be `wp-content` it can be `abcd`.

There are constants that a developer can change like `WP_CONTENT_DIR`.

Use `POLYLANG_VERSION` or even `$filepath = str_replace('woo-poly-integration/','polylang/polylang.php',plugin_dir_path(Hyyan_WPI_DIR));`

### PR DESCRIPTION
**Pull request by ahmedofali**
This pull request fixes #312 . Woocommerce and Polylang detection if they are installed as mu-plugins

#### What's Included in This Pull Request

* Detect woocommerce and polylang if installed as mu-plugins
* Change the way of checking woocommerce and polylang versions and existence

### CODE REVIEW

**Comment by Jon007** [comment]
thanks for contribution but see #312 - this file detection is classed as a bug - it should be replaced by smarter test functions which don't rely on the file paths or names

**Comment by ahmedofali** [comment]
This pull request fixes Issue #312

**Comment by Jon007** [comment]
It's looking good!
@hyyan - another one ready to go here!

**Comment by hyyan** [comment]
@ahmedofali Thank you for your valuable contribution 
@Jon007 Thank you for testing

**Pull request merged**
