### PR TITLE
Fix error on non-product post save

### PR DESCRIPTION
**Pull request by TeemuSuoranta**
Hi!

I'm getting 502 error on post save (locally) if I'm trying to save any other post type than products. Saving terms or products worked fine.

WP: 4.6.1
WC: 2.6.7
Polylang: 2.0.7
Woo-Poly-Integration: 0.28

I traced the problem to Product.php that has code that is run in every post type. I made a subtle changes to Meta.php and Variable.php that will return if the post type is not product. Please, check this out and tell me if this is causing some troubles that I didn't see.

### CODE REVIEW

**Comment by decarvalhoaa** [comment]
These changes should create any issue. Will try to test it tomorrow. But can't understand why without these changes, would it cause 502 errors.

**Comment by hyyan** [comment]
@TeemuSuoranta  I can not mark this as a valid issue , I have just tested this in my local installation and everything seems to work as expected No 502 error , It must be something wrong in the created custom post type and as @decarvalhoaa has said this PR will cause other issues , could you please past the whole error message you are getting .

**Comment by TeemuSuoranta** [comment]
I'll need to do more testing on this. I was getting this error on my vagrant based development environment and I got it even when I switched to default theme and disabled all other plugins than WC, Polylang and this. Adding the fixes included or commenting off these two files fixed the problem. My error log didn't show anything useful. 502 might really be PHP error that happens somewhere. All I knew was having these two files were the dirrenece between error and no error.

I'll need to do more testing on this. I'll try the same on MAMP based environment and in staging server. If I can't get same errors there, the problem might really be somewhere in my environment.  I will take a closer look and let you know what I find.

**Comment by TeemuSuoranta** [comment]
I took a closer look now. I can get rid of the problem locally by switching PHP version to 5.6 (was 7.0). I tested it with the latest version of plugin (0.29). The staging server works well with PHP 7.0, though. PHP error log has nothing but NGINX error log had following error (cleaned the IP and site name):

`2016/11/07 06:59:45 [error] 2967#0: *362 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: , request: "POST /wp-admin/admin-ajax.php HTTP/1.1", upstream: "http://127.0.0.1:1337/wp-admin/admin-ajax.php", host: "site.local", referrer: "https://site.local/wp-admin/post.php?post=11095&action=edit"`

I think we may close this PR here. The only thing that bugs me is why the error only happened to other post types than products and that I could fix it in code. The plugin itself runs with newest versions of WP, other plugins and PHP7 in staging, so there shouldn't be problems in there. Sorry for not testing this enough before sending the PR.

**Pull request closed without merging**
