### PR TITLE
Update files to replace deprecated jQuery methods

### PR DESCRIPTION
**Pull request by mrleemon**
Replace deprecated `.change()` event handler with recommended `.on('change')`
As of jQuery 3.0, the `$(handler)` syntax is recommended instead of the classic `$(document).ready(handler)` syntax

### CODE REVIEW

**Comment by mrleemon** [comment]
@Jon007, can you run the minimize script to create the `Variables.min.js` version, please?
Thanks

**Comment by Jon007** [comment]
@mrleemon  I don't have a standard script for that - just use any of the websites offering that functionality like jscompress.com etc

**Comment by mrleemon** [comment]
Done!

**Comment by mrleemon** [comment]
I replaced more deprecated methods in more files

**Comment by Jon007** [comment]
excellent, thanks @mrleemon

**Pull request merged**
