### PR TITLE
Nicer readme

### PR DESCRIPTION
**Pull request by szepeviktor**
- capitalize P
- unlink the title

### CODE REVIEW

**Comment by hyyan** [comment]
@szepeviktor Thanks for the PR , but why to unlink the title ?!

**Comment by szepeviktor** [comment]
Have you seen a readme with a linked title?

**Comment by szepeviktor** [comment]
I looks like a big blue monster.

**Comment by hyyan** [comment]
@szepeviktor Haha, OK the PR accepted, Thanks :)

**Pull request merged**
