### PR TITLE
Generate Coupon Strings

### LINKED ISSUE #215: Pull request for string generations of coupons
https://github.com/hyyan/woo-poly-integration/pull/214

### PR DESCRIPTION
**Pull request by midorikocak**
This pull request fixes #215 

#### What's Included in This Pull Request

* Coupon::registerCouponStringsForTranslation()
* Coupon::getCoupons()

### CODE REVIEW

**Comment by Jon007** [comment]
Hi, I tested this and had a number of small issues:

1. the string translations are registered but not used.  To use the string translations you would have to filter something like this:

```
            add_filter('woocommerce_coupon_get_description', array($this, 'translateDescription'), 10, 2);
            add_filter('woocommerce_coupon_get_code', array($this, 'translateCode'), 10, 2);
    
    /**
     * translate coupon description.
     *
     * @param string      $value    
     * @param \WC_Coupon $coupon
     *
     * @return string
     */
    public function translateDescription($value, $coupon)
    {
        return pll__($value);
    }
    /**
     * translate coupon code.
     *
     * @param string      $value    
     * @param \WC_Coupon $coupon
     *
     * @return string
     */
    public function translateCode($value, $coupon)
    {
        //unfortunately translating the value breaks other functions which use the value as a key
        return pll__($value);
    }


```

2. unfortunately translating the value breaks other functions since the coupon code is also used as a key to find the coupon, it needs to be untranslated in this context

3. coupon codes are formatted to lower case etc with 3 filters applied by woocommerce
it may be sensible to register the strings as eg:
```
            foreach ($coupons as $coupon) {
                $code = wc_format_coupon_code($coupon->post_title);
                pll_register_string($code, $code, 
                    __('Woocommerce Coupon Names', 'woo-poly-integration'));
                pll_register_string($code . '_description', $coupon->post_excerpt, 
                    __('Woocommerce Coupon Names', 'woo-poly-integration'), true);
            }
```
However, once I got points 1. and 3. working, I found that some code was broken due to point 2

**Comment by Jon007** [comment]
@midorikocak  
Here is a slightly better version of coupon.php which only filters the display of the coupon woocommerce_cart_totals_coupon_label rather than the code, please try this:

```
<?php

/**
 * This file is part of the hyyan/woo-poly-integration plugin.
 * (c) Hyyan Abo Fakher <hyyanaf@gmail.com>.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Hyyan\WPI;

use Hyyan\WPI\Admin\Settings;
use Hyyan\WPI\Admin\Features;
use Hyyan\WPI\Utilities;

/**
 * Coupon.
 *
 * Handle coupon with products translations
 *
 * @author Hyyan Abo Fakher <hyyanaf@gmail.com>
 */
class Coupon
{

    /**
     * Construct object.
     */
    public function __construct()
    {
        if ('on' === Settings::getOption('coupons', Features::getID(), 'on')) {
            add_action('woocommerce_coupon_loaded', array($this, 'couponLoaded'));
            
            add_action('wp_loaded', array($this, 'registerCouponStringsForTranslation'));        
            
            add_filter('woocommerce_coupon_get_description', array($this, 'translateDescription'), 10, 2);
            //apply filter with priority after woocommerce-auto-added-coupons
            add_filter('woocommerce_cart_totals_coupon_label', array($this, 'translateLabel'), 20, 2);
        }
        
    }
    
    /**
     * translate coupon description.
     *
     * @param string      $value    
     * @param \WC_Coupon $coupon
     *
     * @return string
     */
    public function translateDescription($value, $coupon)
    {
        return pll__($value);
    }
    /**
     * translate coupon code.
     *
     * @param string      $value    
     * @param \WC_Coupon $coupon
     *
     * @return string
     */
    public function translateLabel($value, $coupon)
    {
        return sprintf( esc_html__( 'Coupon: %s', 'woocommerce' ), 
            pll__( \get_post( $coupon->get_id() )->post_title ) );
    }
    
    /**
     * Register coupon titles adn descriptions in Polylang's Strings translations table.
     */
    public function registerCouponStringsForTranslation()
    {
        if (function_exists('pll_register_string')) {
            $coupons = $this->getCoupons();
            
            foreach ($coupons as $coupon) {
                //$code = wc_format_coupon_code($coupon->post_title);
                pll_register_string($coupon->post_name, $coupon->post_title, 
                    __('Woocommerce Coupon Names', 'woo-poly-integration'));
                pll_register_string($coupon->post_name . '_description', $coupon->post_excerpt, 
                    __('Woocommerce Coupon Names', 'woo-poly-integration'), true);
            }
        }
    }
    
     /**
     * Helper function - Gets the coupons enabled in the shop.
     *
     * @return array $coupons Coupons settings including post_type, post_excerpt and post_title
     */
    private function getCoupons(){
        global $woocommerce;
        
        $args = array(
            'posts_per_page'   => -1,
            'orderby'          => 'title',
            'order'            => 'asc',
            'post_type'        => 'shop_coupon',
            'post_status'      => 'publish',
        );
    
        $coupons = get_posts( $args );
        return $coupons;
    }
    
    
    /**
     * Extend the coupon to include porducts translations.
     *
     * @param \WC_Coupon $coupon
     *
     * @return \WC_Coupon
     */
    public function couponLoaded(\WC_Coupon $coupon)
    {
        $productIDS                  = array();
        $excludeProductIDS           = array();
        $productCategoriesIDS        = array();
        $excludeProductCategoriesIDS = array();

        foreach ($coupon->get_product_ids() as $id) {
            foreach ($this->getProductPostTranslationIDS($id) as $_id) {
                $productIDS[] = $_id;
            }
        }
        foreach ($coupon->get_excluded_product_ids() as $id) {
            foreach ($this->getProductPostTranslationIDS($id) as $_id) {
                $excludeProductIDS[] = $_id;
            }
        }

        foreach ($coupon->get_product_categories() as $id) {
            foreach ($this->getProductTermTranslationIDS($id) as $_id) {
                $productCategoriesIDS[] = $_id;
            }
        }

        foreach ($coupon->get_excluded_product_categories() as $id) {
            foreach ($this->getProductTermTranslationIDS($id) as $_id) {
                $excludeProductCategoriesIDS[] = $_id;
            }
        }

        $coupon->set_product_ids($productIDS);
        $coupon->set_excluded_product_ids($excludeProductIDS);
        $coupon->set_product_categories($productCategoriesIDS);
        $coupon->set_excluded_product_categories($excludeProductCategoriesIDS);

        return $coupon;
    }


    /**
     * Get array of product translations IDS.
     *
     * @param int $ID the product ID
     *
     * @return array array contains all translation IDS for the given product
     */
    protected function getProductPostTranslationIDS($ID)
    {
        $result  = array($ID);
        $product = wc_get_product($ID);

        if ($product && $product->get_type() === 'variation') {
            $IDS = Product\Variation::getRelatedVariation($ID, true);
            if (is_array($IDS)) {
                $result = array_merge($result, $IDS);
            }
        } else {
            $IDS = Utilities::getProductTranslationsArrayByID($ID);
            if (is_array($IDS)) {
                $result = array_merge($result, $IDS);
            }
        }

        return $IDS ? $IDS : array($ID);
    }

    /**
     * Get array of term translations IDS.
     *
     * @param int $ID the term ID
     *
     * @return array array contains all translation IDS for the given term
     */
    protected function getProductTermTranslationIDS($ID)
    {
        $IDS = Utilities::getTermTranslationsArrayByID($ID);

        return $IDS ? $IDS : array($ID);
    }

}

```

**Comment by Jon007** [comment]
this is now superseded by more complete solution checked into 1.0.2, please try that!
https://github.com/hyyan/woo-poly-integration/tree/1.0.2

**Comment by midorikocak** [comment]
Thank you.

**Pull request closed without merging**
