### PR TITLE
Added support for cart item custom variation types

### PR DESCRIPTION
**Pull request by Sti3bas**
This pull request fixes WooCommerce Subscriptions interval on cart item.

Before(every 3 months is selected, but shows every 6):
screen shot 2017-08-30 at 15 06 13

After: 
screen shot 2017-08-30 at 15 04 51

### CODE REVIEW

**Comment by Jon007** [comment]
Is there a related issue for this?
So the plugin creates a custom post type, which isn't called 'variation' so not picked up by the variation handling code, but does contain the string 'variation'.

@Sti3bas, 
There is quite a bit of code for variations in different places, this is just for the Cart, I imagine there would be other problems.
Doesn't a similar issue apply in Orders (user and admin view), and Emails?

**Comment by Sti3bas** [comment]
No, I haven't created an issue.

I haven't noticed any other problems in the other places.

There are only two places where variation type is hardcoded:
Hyyan\WPI\Cart@translateCartItemProduct()
Hyyan\WPI\Coupon@getProductPostTranslationIDS()

I've committed coupon fix too.

**Comment by Jon007** [comment]
>There are only two places where variation type is hardcoded
I think it's luck rather than design, that the code in some places is looking for children of a Variable product without checking the type.

However there are more cases so there should be more problems:
- variation.php has  'post_type' => 'product_variation',
- there are also uses of WC_Product_Variation such as instanceof \WC_Product_Variation
- variable.php             $count = wp_count_posts('product_variation');

Please open an issue for this, at the moment it's invisible on the issues list.
Without really understanding what the use case is, it is hard to advise on the possible issues and best solution.

**Comment by Sti3bas** [comment]
In WooCommerce Subscriptions case it's stored as 'product_variation' and it extends WC_Product_Variation class, so everything works out of the box, except these two hardcoded places.

**Comment by hyyan** [comment]
> There are only two places where variation type is hardcoded
@Sti3bas I agree with @Jon007, it's luck rather than design. I believe this PR will not find its way to the master branch even though it might be working because the use case behind it is not clear enough.

@Jon007 do you think we need to update the code to handle new product types other than 'variation` and `simple` cause this is possible with woocommerce

**Comment by Sti3bas** [comment]
@hyyan what do you mean by "the use case behind it is not clear enough"?

This PR adds compatibility with WooCommerce Subscriptions plugin (https://woocommerce.com/products/woocommerce-subscriptions/).

**Comment by hyyan** [comment]
@Sti3bas what I meant is that the PR tries to resolve a specific plugin(WooCommerce Subscriptions) problem which is we do not support in the first place and it seems to add new custom post/ product type called Variable Subscriptions, now your solution might work just fine for your case but it would not for others. cause not all plugins use the same pattern in naming custom posts, the ideal solution would be adding hooks allowing other plugins to extend the supported product types in the plugin and which your PR seems not to add

**Comment by Jon007** [comment]
@Sti3bas I see now you are referring a WooCommerce official plugin (this was not obvious as there are many plugins that claim to offer subscriptions functionality compatible with WooCommerce).
However as it is a WooCommerce paid plugin and not open source, other people can't see or test what it does, so it would be good to have an Issue opened to explain how this is expected to work.

Unless you are representing the WooCommerce team, it's also a concern that the solution is not tested or supported by the WooCommerce team and cannot be supported by the main contributors of this plugin. Contributors to this plugin literally can't support it as they have no access to the WooCommerce Subscriptions plugin or code.

It might be best to turn into a more generic use case and find another [open-source] plugin to test with, and at least add a documentation note to the wiki on what types of custom products can be expected to work.

**Comment by Sti3bas** [comment]
It's licensed under GPLv3 license, so you can definitely use this plugin: https://github.com/wp-premium/woocommerce-subscriptions

**Comment by Jon007** [comment]
Hmmm... on the previous link you sent it is $199 every year per single site!
So you are saying that the premium plugins can actually be used for free because someone has published a copy of them with a GPLv3 licence?

All this should be clarified in an issue write-up rather than this discussion.

**Pull request closed without merging**
