### PR TITLE
Proposed new release 0.29

### PR DESCRIPTION
**Pull request by decarvalhoaa**
- Fixed PHP notice due to Polylang deprecated functions
- Fixed Wordpress database error in reports page
- Fixed missing argument warning in order detailspage and emails
- Fixed strpos() empty needle warning for empty endpoints
- Fixed removing email instructions from 3rd party payment gateways

### CODE REVIEW

**Comment by decarvalhoaa** [comment]
Stuff changed (update):
- Fixed PHP notice due to Polylang deprecated functions
- Fixed Wordpress database error in reports page
- Fixed missing argument warning in order detailspage and emails
- Fixed strpos() empty needle warning for empty endpoints
- Fixed removing email instructions from 3rd party payment gateways
- Fixed not detecting whether polylang pro is active

**Comment by decarvalhoaa** [comment]
One more fix:

- Fixed PHP notice in Reports when products don't have translations

**Comment by decarvalhoaa** [comment]
@hyyan At the end of the day, it is up to you whether you want to support previous versions of WooCommerce and Poylang. 

I will remove the plugin check in the Reports class, but I would leave the function definition in the Utilities class - it can be handy in the future. It doesn't hurt.

Just as background information:  I assumed a support policy n-1 major release. Basically because I never upgrade to a major release of a plugin nor the Wordpress core, until there is 1 or 2 bug-fixes releases out. Generally the new major releases are still a bit buggy and I like to wait until they are bit more stable - it helps reducing the testing and troubleshooting time. 
I don't like either to upgrade more than 1 plugin at the time to isolate changes - it helps with troubleshooting.

**Comment by hyyan** [comment]
@decarvalhoaa In matter of fact , you have a point of view , it is not how I have planned for the versioning , but thinks are getting more and more complicated in here , we need this for testing and troubleshooting

I would say we keep it this way , it is better 

Thanks @decarvalhoaa , I will do the merge at the end of the day

**Comment by decarvalhoaa** [comment]
ops!! I just remove the check! Shall I reverse the last commit?! I will wait for your GO before doing anything this time

**Comment by hyyan** [comment]
@decarvalhoaa  NP , just revert please

**Comment by decarvalhoaa** [comment]
Ok, I did a hard reset on the HEAD to keep the commit history clean.

**Comment by hyyan** [comment]
@decarvalhoaa  Sound perfect, Great Work so far thanks 👍

**Comment by decarvalhoaa** [comment]
**0.29 (Not released) Changelog**

* Fix PHP notice in Reports when products dont have translations
* Fixed PHP notice due to Polylang deprecated functions
* Fixed Wordpress database error in reports page
* Fixed missing argument warning in order detailspage and emails
* Fixed strpos() empty needle warning for empty endpoints
* Fixed removing email instructions from 3rd party payment gateways
* Fixed not detecting whether polylang pro is active
* Fixed unable to unselect a complete settings section [Issue #51](https://github.com/hyyan/woo-poly-integration/issues/51)
* Tested and confirmed working on WordPress 4.6.1, Polylang 2.0.7 and WooCommerce 2.6.7

**Comment by hyyan** [comment]
Awesome work @decarvalhoaa  , Thanks  🍺

**Pull request merged**
